CREATE USER I2B2PM WITH PASSWORD 'I2B2PM';
CREATE SCHEMA I2B2PM AUTHORIZATION I2B2PM;
GRANT ALL ON SCHEMA I2B2PM to I2B2PM;

CREATE USER I2B2HIVE WITH PASSWORD 'I2B2HIVE';
CREATE SCHEMA I2B2HIVE AUTHORIZATION I2B2HIVE;
GRANT ALL ON SCHEMA I2B2HIVE to I2B2HIVE;

CREATE USER I2B2DEMODATA WITH PASSWORD 'I2B2DEMODATA';
CREATE SCHEMA I2B2DEMODATA AUTHORIZATION I2B2DEMODATA;
GRANT ALL ON SCHEMA I2B2DEMODATA to I2B2DEMODATA;

CREATE USER I2B2METADATA WITH PASSWORD 'I2B2METADATA';
CREATE SCHEMA I2B2METADATA AUTHORIZATION I2B2METADATA;
GRANT ALL ON SCHEMA I2B2METADATA to I2B2METADATA;

CREATE USER I2B2WORKDATA WITH PASSWORD 'I2B2WORKDATA';
CREATE SCHEMA I2B2WORKDATA AUTHORIZATION I2B2WORKDATA;
GRANT ALL ON SCHEMA I2B2WORKDATA to I2B2WORKDATA;

COMMIT;
