
DROP SCHEMA IF EXISTS  I2B2PM;
DROP USER IF EXISTS  I2B2PM;

DROP SCHEMA IF EXISTS  I2B2HIVE;
DROP USER IF EXISTS  I2B2HIVE;

DROP SCHEMA IF EXISTS  I2B2DEMODATA;
DROP USER IF EXISTS  I2B2DEMODATA;

DROP SCHEMA IF EXISTS  I2B2METADATA;
DROP USER IF EXISTS  I2B2METADATA;

DROP SCHEMA IF EXISTS  I2B2WORKDATA;
DROP USER IF EXISTS  I2B2WORKDATA;

COMMIT;
