
DROP SCHEMA IF EXISTS I2B2PM CASCADE;
DROP USER IF EXISTS I2B2PM;

DROP SCHEMA IF EXISTS  I2B2HIVE CASCADE;
DROP USER IF EXISTS  I2B2HIVE;

DROP SCHEMA IF EXISTS  I2B2DEMODATA CASCADE;
DROP USER IF EXISTS  I2B2DEMODATA;

DROP SCHEMA IF EXISTS  I2B2METADATA CASCADE;
DROP USER IF EXISTS  I2B2METADATA;

DROP SCHEMA IF EXISTS  I2B2WORKDATA CASCADE;
DROP USER IF EXISTS  I2B2WORKDATA;

COMMIT;
